# Generated by Django 4.2.3 on 2023-08-29 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_end_date_alter_auction_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
